name: environments workflow

on: [push]

jobs:
  windows-job:
    runs-on: windows-latest
    steps:
      - name: using powershell
        shell: pwsh
        run: |
          Get-Location
          Write-Output "Finished at $(Get-Date)"

  macos-job:
    needs: windows-job
    runs-on: macos-latest
    steps:
      - name: running in mac
        shell: bash
        run: |
          echo Hello world
          echo "Finished at $(date)"

  linux-job:
    needs: macos-job
    runs-on: ubuntu-latest
    steps:
      - name: running in ubuntu
        shell: bash
        run: |
          echo Hello world
          echo "Finished at $(date)"

