name: Parallel and Sequential Jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project
      run: |
        echo "Building the project..."
        mkdir -p build
        echo "Build output" > build/output.txt
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./build

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run unit tests
      run: echo "Running unit tests..."

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run integration tests
      run: echo "Running integration tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./build
    - name: List build directory
      run: |
        echo "Listing contents of the build directory:"
        ls -al ./build
    - name: Deploy to production
      run: echo "Deploying to production..."

