name: New workflow 
run-name: New workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run build
              run: echo "Build app"


    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run some tests
              run: echo "Run some tests"

